### ISSUE TITLE
Allow for naming of queries with `createServerQueries`

### ISSUE THREAD

**Issue by dihmeetree** [vishalbalaji/trpc-svelte-query-adapter#21]
Thanks for this library first of all, it's great! 😃 

Instead of doing this:
```ts
export const load: PageLoad = async (event) => {
  const { queryClient } = await event.parent();
  const api = trpc(event, queryClient);
  return {
    queries: await api.createServerQueries((t) => [
      t.public.todos.list(),
      t.public.hello.get()
    ])
  };
};
```

I'd like to be able to name the queries like so:
```ts
export const load: PageLoad = async (event) => {
  const { queryClient } = await event.parent();
  const api = trpc(event, queryClient);
  return {
    queries: await api.createServerQueries((t) => [
      {
        listTodos: t.public.todos.list(),
        getHello: t.public.hello.get()
      }
    ])
  };
};
```

Right now i'm doing something like this on the frontend
```ts
<script lang="ts">
  import { page } from '$app/stores';
  import { trpc } from '$lib/trpc/client';
  import type { PageData } from './$types';

  export let data: PageData;

  const queries = data.queries();

  $: listTodos = $queries[0];
  $: getHello = $queries[1];

  const api = trpc($page);
  const addTodo = api.public.todos.add.createMutation();
  const deleteTodo = api.public.todos.delete.createMutation();
</script>
  ```
  
I'd love to be able to access the queries directly like so:
```ts
$queries.listTodos
```
and
```ts
$queries.getHello
```

**Comment by vishalbalaji** [comment]
Hi, glad you liked the library 🤗.

This library tries not to stray too far away from how Tanstack query does things. To do this, we might have to significantly deviate from what `createQueries` returns by default, which is not really desirable since it would mean users having to adapt to non-standard behaviour that exists just for this library.

Personally, I just get over this through just de-structuring the query, like so:

```ts
const [fooQuery, barQuery] = $queries;
```

I don't think this is something I would be adding to this library, but thanks a lot for the suggestion!

**Comment by dihmeetree** [comment]
Ahhhhh destructuring right! Sometimes I forget the basics haha. 

This will work perfect! Thank you for the suggestion 😃
